export type Product = {
  id: number
  name: string
  price: string
  priceNum: number
  category: string
  image: string
  brand?: string
  material?: string
  waterResistance?: string
  warranty?: string
  description?: string
  features?: string[]
  images?: string[]
  subcategory?: string
  tags?: string[]
  discountPercentage?: number
  badges?: string[]
  inventory?: { stock?: number; sku?: string }
  size?: string
  limited?: boolean
}

export const products: Product[] = [
  // Popular Products (Homepage)
  {
    id: 1,
    name: "Phoenix II Rosegold",
    price: "KSh8,550.00",
    priceNum: 8550,
    category: "Women's Watch",
    brand: "Rolex",
    material: "Leather",
    waterResistance: "5 ATM",
    warranty: "1 Year",
    size: "36mm",
    limited: false,
    description: "Elegant rose gold timepiece with a sophisticated dial and premium leather strap. Perfect for both casual and formal occasions.",
    features: ["Japanese Movement", "Scratch-resistant glass", "Adjustable strap", "Free battery replacement"],
    image: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&q=80",
  },
  {
    id: 2,
    name: "Vega Black",
    price: "KSh8,550.00",
    priceNum: 8550,
    category: "Men's Watch",
    brand: "Omega",
    material: "Metallic",
    waterResistance: "10 ATM",
    warranty: "1 Year",
    size: "42mm",
    limited: false,
    description: "Bold black watch with metallic accents and modern design. A statement piece for the contemporary man.",
    features: ["Swiss Movement", "Chronograph function", "Stainless steel case", "Free battery replacement"],
    image: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=600&q=80",
  },
  {
    id: 3,
    name: "Aurora III Rose Gold M",
    price: "KSh13,500.00",
    priceNum: 13500,
    category: "Women's Watch",
    brand: "Cartier",
    material: "Metallic",
    waterResistance: "5 ATM",
    warranty: "1 Year",
    size: "34mm",
    limited: true,
    description: "Premium rose gold watch with intricate detailing and luxurious finish. The epitome of elegance and style.",
    features: ["Japanese Movement", "Diamond-cut crystals", "Rose gold plating", "Free battery replacement"],
    image: "https://images.unsplash.com/photo-1622434641406-a158123450f9?w=600&q=80",
  },
  {
    id: 4,
    name: "Phoenix II Black-Blue L",
    price: "KSh8,550.00",
    priceNum: 8550,
    category: "Men's Watch",
    brand: "Tag Heuer",
    material: "Leather",
    waterResistance: "10 ATM",
    warranty: "1 Year",
    size: "44mm",
    limited: false,
    description: "Stylish black and blue watch with premium craftsmanship. Perfect for the modern gentleman.",
    features: ["Swiss Movement", "Water resistant", "Durable leather strap", "Free battery replacement"],
    image: "https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?w=600&q=80",
  },
  
  // Shop Page Products - Men's Watches
  {
    id: 5,
    name: "Classic Leather",
    price: "KSh8,500.00",
    priceNum: 8500,
    category: "Men's Watch",
    brand: "Rolex",
    size: "42mm",
    limited: false,
    material: "Leather",
    waterResistance: "5 ATM",
    warranty: "1 Year",
    description: "Timeless classic leather watch with sophisticated design and reliable Japanese movement.",
    features: ["Japanese Movement", "Genuine leather strap", "Water resistant", "Free battery replacement"],
    image: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=600&q=80",
  },
  {
    id: 6,
    name: "Sport Chronograph",
    price: "KSh12,000.00",
    priceNum: 12000,
    category: "Men's Watch",
    brand: "Omega",
    size: "44mm",
    limited: true,
    material: "Stainless Steel",
    waterResistance: "10 ATM",
    warranty: "2 Years",
    description: "High-performance chronograph with precision timing and sporty aesthetic.",
    features: ["Swiss Movement", "Chronograph function", "Tachymeter scale", "Free battery replacement"],
    image: "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=600&q=80",
  },
  {
    id: 7,
    name: "Executive Black",
    price: "KSh9,500.00",
    priceNum: 9500,
    category: "Men's Watch",
    brand: "Tag Heuer",
    size: "40mm",
    limited: false,
    material: "Stainless Steel",
    waterResistance: "5 ATM",
    warranty: "1 Year",
    description: "Elegant executive watch perfect for business and formal occasions.",
    features: ["Swiss Movement", "Scratch-resistant sapphire crystal", "Black dial", "Free battery replacement"],
    image: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&q=80",
  },
  {
    id: 8,
    name: "Diver Pro",
    price: "KSh15,000.00",
    priceNum: 15000,
    category: "Men's Watch",
    brand: "Seiko",
    size: "45mm",
    limited: true,
    material: "Stainless Steel",
    waterResistance: "20 ATM",
    warranty: "2 Years",
    description: "Professional diving watch with exceptional water resistance and luminous markers.",
    features: ["Automatic Movement", "Rotating bezel", "Super-LumiNova hands", "Free battery replacement"],
    image: "https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=600&q=80",
  },
  {
    id: 9,
    name: "Aviator Steel",
    price: "KSh11,000.00",
    priceNum: 11000,
    category: "Men's Watch",
    brand: "Citizen",
    size: "43mm",
    limited: false,
    material: "Stainless Steel",
    waterResistance: "10 ATM",
    warranty: "1 Year",
    description: "Aviation-inspired watch with bold design and precise timekeeping.",
    features: ["Eco-Drive Movement", "Date display", "Pilot-style dial", "Free battery replacement"],
    image: "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=600&q=80",
  },
  {
    id: 10,
    name: "Heritage Brown",
    price: "KSh7,800.00",
    priceNum: 7800,
    category: "Men's Watch",
    brand: "Fossil",
    size: "41mm",
    limited: false,
    material: "Leather",
    waterResistance: "5 ATM",
    warranty: "1 Year",
    description: "Vintage-inspired watch with brown leather strap and classic styling.",
    features: ["Quartz Movement", "Leather strap", "Vintage dial design", "Free battery replacement"],
    image: "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=600&q=80",
  },
  
  // Women's Watches
  {
    id: 41,
    name: "Rose Gold Elegance",
    price: "KSh6,500.00",
    priceNum: 6500,
    category: "Women's Watch",
    brand: "Michael Kors",
    size: "36mm",
    limited: false,
    material: "Stainless Steel",
    waterResistance: "5 ATM",
    warranty: "1 Year",
    description: "Elegant rose gold watch with refined details and feminine charm.",
    features: ["Quartz Movement", "Rose gold plating", "Crystal accents", "Free battery replacement"],
    image: "https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=600&q=80",
  },
  {
    id: 42,
    name: "Diamond Bezel",
    price: "KSh9,200.00",
    priceNum: 9200,
    category: "Women's Watch",
    brand: "Cartier",
    size: "32mm",
    limited: true,
    material: "Stainless Steel",
    waterResistance: "3 ATM",
    warranty: "2 Years",
    description: "Luxurious watch with diamond-studded bezel and premium craftsmanship.",
    features: ["Swiss Movement", "Diamond bezel", "Mother-of-pearl dial", "Free battery replacement"],
    image: "https://images.unsplash.com/photo-1588098710871-8ee69776e45c?w=600&q=80",
  },
  {
    id: 43,
    name: "Slim Leather",
    price: "KSh4,800.00",
    priceNum: 4800,
    category: "Women's Watch",
    brand: "Daniel Wellington",
    size: "34mm",
    limited: false,
    material: "Leather",
    waterResistance: "3 ATM",
    warranty: "1 Year",
    description: "Minimalist slim watch with genuine leather strap and clean design.",
    features: ["Quartz Movement", "Slim profile", "Interchangeable straps", "Free battery replacement"],
    image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=600&q=80",
  },
  {
    id: 44,
    name: "Pearl Mother",
    price: "KSh8,500.00",
    priceNum: 8500,
    category: "Women's Watch",
    brand: "Tissot",
    size: "30mm",
    limited: true,
    material: "Stainless Steel",
    waterResistance: "5 ATM",
    warranty: "2 Years",
    description: "Exquisite watch with mother-of-pearl dial and delicate design.",
    features: ["Swiss Quartz Movement", "Mother-of-pearl dial", "Sapphire crystal", "Free battery replacement"],
    image: "https://images.unsplash.com/photo-1610456123037-7d2be1a24e0d?w=600&q=80",
  },
  
  // Smart Watches
  {
    id: 45,
    name: "Apple Watch Series 9",
    price: "KSh7,800.00",
    priceNum: 7800,
    category: "Smart Watch",
    brand: "Apple",
    size: "41mm",
    limited: false,
    material: "Aluminum",
    waterResistance: "5 ATM",
    warranty: "1 Year",
    description: "Latest Apple Watch with advanced health tracking and connectivity features.",
    features: ["Always-On Retina Display", "Heart Rate Monitor", "GPS", "Water resistant"],
    image: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600&q=80",
  },
  {
    id: 46,
    name: "Galaxy Watch 6",
    price: "KSh6,200.00",
    priceNum: 6200,
    category: "Smart Watch",
    brand: "Samsung",
    size: "40mm",
    limited: false,
    material: "Aluminum",
    waterResistance: "5 ATM",
    warranty: "1 Year",
    description: "Samsung's flagship smartwatch with comprehensive health and fitness tracking.",
    features: ["AMOLED Display", "Sleep Tracking", "GPS", "Water resistant"],
    image: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&q=80",
  },
  
  // Accessories - Bracelets
  {
    id: 81,
    name: "Love Bracelet",
    price: "KSh8,500.00",
    priceNum: 8500,
    category: "Bracelet",
    brand: "Cartier",
    size: "Medium",
    limited: true,
    material: "Gold Plated",
    description: "Iconic love bracelet with screw motif and timeless design.",
    features: ["18K Gold Plated", "Signature screw design", "Includes screwdriver", "Gift box included"],
    image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&q=80",
  },
  {
    id: 82,
    name: "Return to Tiffany",
    price: "KSh6,200.00",
    priceNum: 6200,
    category: "Bracelet",
    brand: "Tiffany & Co",
    size: "Small",
    limited: false,
    material: "Sterling Silver",
    description: "Classic Tiffany bracelet with heart tag charm and elegant chain.",
    features: ["Sterling Silver", "Heart tag charm", "Adjustable length", "Gift box included"],
    image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&q=80",
  },
  {
    id: 83,
    name: "Charm Bracelet",
    price: "KSh3,500.00",
    priceNum: 3500,
    category: "Bracelet",
    brand: "Pandora",
    size: "Medium",
    limited: false,
    material: "Sterling Silver",
    description: "Customizable charm bracelet perfect for collecting meaningful charms.",
    features: ["Sterling Silver", "Compatible with Pandora charms", "Secure clasp", "Gift box included"],
    image: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=600&q=80",
  },
  
  // Watch Straps
  {
    id: 84,
    name: "Leather Watch Strap",
    price: "KSh1,200.00",
    priceNum: 1200,
    category: "Strap",
    brand: "Universal",
    size: "20mm",
    limited: false,
    material: "Genuine Leather",
    description: "Premium leather watch strap compatible with most standard watches.",
    features: ["Genuine Leather", "Multiple colors", "Quick release pins", "Universal fit"],
    image: "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=600&q=80",
  },
  {
    id: 85,
    name: "Metal Link Bracelet",
    price: "KSh2,800.00",
    priceNum: 2800,
    category: "Strap",
    brand: "Universal",
    size: "22mm",
    limited: false,
    material: "Stainless Steel",
    description: "Stainless steel link bracelet with adjustable sizing.",
    features: ["Stainless Steel", "Butterfly clasp", "Adjustable links", "Universal fit"],
    image: "https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?w=600&q=80",
  },
  
  // Bangles
  {
    id: 86,
    name: "Gold Bangle",
    price: "KSh4,500.00",
    priceNum: 4500,
    category: "Bangle",
    brand: "Universal",
    size: "Medium",
    limited: false,
    material: "Gold Plated",
    description: "Elegant gold bangle perfect for stacking or wearing solo.",
    features: ["18K Gold Plated", "Smooth finish", "Comfortable fit", "Gift box included"],
    image: "https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?w=600&q=80",
  },
]

export function getProductById(id: number) {
  return products.find((p) => p.id === id)
}

export function getProductsByCategory(category: string) {
  return products.filter((p) => p.category?.toLowerCase() === category.toLowerCase())
}
