export type Product = {
  id: number
  name: string
  price: string
  priceNum: number
  category: string
  image: string
  brand?: string
  material?: string
  waterResistance?: string
  warranty?: string
  description?: string
  features?: string[]
  images?: string[]
  subcategory?: string
  tags?: string[]
  discountPercentage?: number
  badges?: string[]
  inventory?: { stock?: number; sku?: string }
  size?: string
  limited?: boolean
}

export const products: Product[] = [
  // Popular Products (Homepage)
  {
    id: 1,
    name: "Phoenix II Rosegold",
    price: "KSh8,550.00",
    priceNum: 8550,
    category: "Women's Watch",
    brand: "Rolex",
    material: "Leather",
    waterResistance: "5 ATM",
    warranty: "1 Year",
    size: "36mm",
    limited: false,
    description: "Elegant rose gold timepiece with a sophisticated dial and premium leather strap. Perfect for both casual and formal occasions.",
    features: ["Japanese Movement", "Scratch-resistant glass", "Adjustable strap", "Free battery replacement"],
    image: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&q=80",
  },
  {
    id: 2,
    name: "Vega Black",
    price: "KSh8,550.00",
    priceNum: 8550,
    category: "Men's Watch",
    brand: "Omega",
    material: "Metallic",
    waterResistance: "10 ATM",
    warranty: "1 Year",
    size: "42mm",
    limited: false,
    description: "Bold black watch with metallic accents and modern design. A statement piece for the contemporary man.",
    features: ["Swiss Movement", "Chronograph function", "Stainless steel case", "Free battery replacement"],
    image: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=600&q=80",
  },
  {
    id: 3,
    name: "Aurora III Rose Gold M",
    price: "KSh13,500.00",
    priceNum: 13500,
    category: "Women's Watch",
    brand: "Cartier",
    material: "Metallic",
    waterResistance: "5 ATM",
    warranty: "1 Year",
    size: "34mm",
    limited: true,
    description: "Premium rose gold watch with intricate detailing and luxurious finish. The epitome of elegance and style.",
    features: ["Japanese Movement", "Diamond-cut crystals", "Rose gold plating", "Free battery replacement"],
    image: "https://images.unsplash.com/photo-1622434641406-a158123450f9?w=600&q=80",
  },
  {
    id: 4,
    name: "Phoenix II Black-Blue L",
    price: "KSh8,550.00",
    priceNum: 8550,
    category: "Men's Watch",
    brand: "Tag Heuer",
    material: "Leather",
    waterResistance: "10 ATM",
    warranty: "1 Year",
    size: "44mm",
    limited: false,
    description: "Stylish black and blue watch with premium craftsmanship. Perfect for the modern gentleman.",
    features: ["Swiss Movement", "Water resistant", "Durable leather strap", "Free battery replacement"],
    image: "https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?w=600&q=80",
  },
  
  // Shop Page Products - Men's Watches
  {
    id: 5,
    name: "Classic Leather",
    price: "KSh8,500.00",
    priceNum: 8500,
    category: "Men's Watch",
    brand: "Rolex",
    size: "42mm",
    limited: false,
    material: "Leather",
    waterResistance: "5 ATM",
    warranty: "1 Year",
    description: "Timeless classic leather watch with sophisticated design and reliable Japanese movement.",
    features: ["Japanese Movement", "Genuine leather strap", "Water resistant", "Free battery replacement"],
    image: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=600&q=80",
  },
  {
    id: 6,
    name: "Sport Chronograph",
    price: "KSh12,000.00",
    priceNum: 12000,
    category: "Men's Watch",
    brand: "Omega",
    size: "44mm",
    limited: true,
    material: "Stainless Steel",
    waterResistance: "10 ATM",
    warranty: "2 Years",
    description: "High-performance chronograph with precision timing and sporty aesthetic.",
    features: ["Swiss Movement", "Chronograph function", "Tachymeter scale", "Free battery replacement"],
    image: "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=600&q=80",
  },
  {
    id: 7,
    name: "Executive Black",
    price: "KSh9,500.00",
    priceNum: 9500,
    category: "Men's Watch",
    brand: "Tag Heuer",
    size: "40mm",
    limited: false,
    material: "Stainless Steel",
    waterResistance: "5 ATM",
    warranty: "1 Year",
    description: "Elegant executive watch perfect for business and formal occasions.",
    features: ["Swiss Movement", "Scratch-resistant sapphire crystal", "Black dial", "Free battery replacement"],
    image: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&q=80",
  },
  {
    id: 8,
    name: "Diver Pro",
    price: "KSh15,000.00",
    priceNum: 15000,
    category: "Men's Watch",
    brand: "Seiko",
    size: "45mm",
    limited: true,
    material: "Stainless Steel",
    waterResistance: "20 ATM",
    warranty: "2 Years",
    description: "Professional diving watch with exceptional water resistance and luminous markers.",
    features: ["Automatic Movement", "Rotating bezel", "Super-LumiNova hands", "Free battery replacement"],
    image: "https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=600&q=80",
  },
  {
    id: 9,
    name: "Aviator Steel",
    price: "KSh11,000.00",
    priceNum: 11000,
    category: "Men's Watch",
    brand: "Citizen",
    size: "43mm",
    limited: false,
    material: "Stainless Steel",
    waterResistance: "10 ATM",
    warranty: "1 Year",
    description: "Aviation-inspired watch with bold design and precise timekeeping.",
    features: ["Eco-Drive Movement", "Date display", "Pilot-style dial", "Free battery replacement"],
    image: "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=600&q=80",
  },
  {
    id: 10,
    name: "Heritage Brown",
    price: "KSh7,800.00",
    priceNum: 7800,
    category: "Men's Watch",
    brand: "Fossil",
    size: "41mm",
    limited: false,
    material: "Leather",
    waterResistance: "5 ATM",
    warranty: "1 Year",
    description: "Vintage-inspired watch with brown leather strap and classic styling.",
    features: ["Quartz Movement", "Leather strap", "Vintage dial design", "Free battery replacement"],
    image: "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=600&q=80",
  },
  
  // Men's Leather Collection (Extended)
  {
    id: 21,
    name: "Classic Leather Black",
    price: "KSh8,500.00",
    priceNum: 8500,
    category: "Men's Watch",
    brand: "Rolex",
    material: "Leather",
    waterResistance: "5 ATM",
    warranty: "2 Years",
    size: "42mm",
    limited: false,
    description: "Classic black leather strap watch with timeless design. Perfect for business and formal wear.",
    features: ["Genuine Leather", "Date display", "Scratch-resistant", "Water-resistant"],
    image: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=600&q=80",
  },
  {
    id: 22,
    name: "Executive Leather Brown",
    price: "KSh9,200.00",
    priceNum: 9200,
    category: "Men's Watch",
    brand: "Omega",
    material: "Leather",
    waterResistance: "5 ATM",
    warranty: "2 Years",
    size: "44mm",
    limited: true,
    description: "Executive brown leather watch with premium craftsmanship. Limited edition sophistication.",
    features: ["Premium Leather", "Chronograph", "Date window", "Limited Edition"],
    image: "https://images.unsplash.com/photo-1533139502658-0198f920d8e8?w=600&q=80",
  },
  {
    id: 23,
    name: "Premium Leather Cognac",
    price: "KSh9,800.00",
    priceNum: 9800,
    category: "Men's Watch",
    brand: "TAG Heuer",
    material: "Leather",
    waterResistance: "10 ATM",
    warranty: "2 Years",
    size: "40mm",
    limited: false,
    description: "Premium cognac leather strap with refined dial. Luxury meets comfort.",
    features: ["Cognac Leather", "Sapphire crystal", "Chronograph", "Water-resistant"],
    image: "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=600&q=80",
  },
  {
    id: 24,
    name: "Vintage Leather Navy",
    price: "KSh8,800.00",
    priceNum: 8800,
    category: "Men's Watch",
    brand: "Patek Philippe",
    material: "Leather",
    waterResistance: "3 ATM",
    warranty: "2 Years",
    size: "42mm",
    limited: false,
    description: "Vintage-inspired navy leather watch. Classic elegance for discerning gentlemen.",
    features: ["Navy Leather", "Vintage design", "Date display", "Handcrafted"],
    image: "https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?w=600&q=80",
  },
  {
    id: 25,
    name: "Elite Leather Burgundy",
    price: "KSh9,500.00",
    priceNum: 9500,
    category: "Men's Watch",
    brand: "Cartier",
    material: "Leather",
    waterResistance: "5 ATM",
    warranty: "2 Years",
    size: "41mm",
    limited: true,
    description: "Elite burgundy leather watch with distinctive character. Limited edition luxury.",
    features: ["Burgundy Leather", "Swiss Movement", "Date window", "Limited Edition"],
    image: "https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?w=600&q=80",
  },
  {
    id: 26,
    name: "Heritage Leather Tan",
    price: "KSh9,000.00",
    priceNum: 9000,
    category: "Men's Watch",
    brand: "Breitling",
    material: "Leather",
    waterResistance: "5 ATM",
    warranty: "2 Years",
    size: "43mm",
    limited: false,
    description: "Heritage tan leather with classic aviation styling. Timeless sophistication.",
    features: ["Tan Leather", "Aviation design", "Luminous hands", "Water-resistant"],
    image: "https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=600&q=80",
  },
  {
    id: 27,
    name: "Sport Chronograph Steel",
    price: "KSh12,500.00",
    priceNum: 12500,
    category: "Men's Watch",
    brand: "Rolex",
    material: "Metallic",
    waterResistance: "20 ATM",
    warranty: "3 Years",
    size: "44mm",
    limited: true,
    description: "Sport chronograph with steel case. Professional performance and style.",
    features: ["Steel case", "Chronograph", "Tachymeter", "Limited Edition"],
    image: "https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=600&q=80",
  },
  {
    id: 28,
    name: "Diver Professional",
    price: "KSh11,200.00",
    priceNum: 11200,
    category: "Men's Watch",
    brand: "Omega",
    material: "Rubber",
    waterResistance: "30 ATM",
    warranty: "3 Years",
    size: "45mm",
    limited: false,
    description: "Professional diver watch with rubber strap. Built for underwater adventures.",
    features: ["Rubber strap", "Rotating bezel", "Luminous", "Professional diver"],
    image: "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=600&q=80",
  },
  {
    id: 29,
    name: "Aviation Pilot Watch",
    price: "KSh10,800.00",
    priceNum: 10800,
    category: "Men's Watch",
    brand: "IWC",
    material: "Canvas",
    waterResistance: "6 ATM",
    warranty: "2 Years",
    size: "46mm",
    limited: false,
    description: "Aviation pilot watch with canvas strap. Precision timing for aviators.",
    features: ["Canvas strap", "Pilot design", "Large dial", "Date display"],
    image: "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=600&q=80",
  },
  {
    id: 30,
    name: "Leather Wallet Brown",
    price: "KSh3,500.00",
    priceNum: 3500,
    category: "Wallet",
    brand: "Fossil",
    material: "Leather",
    limited: false,
    description: "Classic brown leather wallet with multiple card slots. Essential accessory.",
    features: ["Genuine leather", "Multiple slots", "Coin pocket", "ID window"],
    image: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&q=80",
  },
  
  // Men's Canvas Collection
  {
    id: 11,
    name: "Atlas Canvas Black",
    price: "KSh6,500.00",
    priceNum: 6500,
    category: "Men's Watch",
    brand: "Timex",
    material: "Canvas",
    waterResistance: "3 ATM",
    warranty: "1 Year",
    size: "42mm",
    limited: false,
    description: "Rugged canvas strap watch perfect for adventure. Durable and comfortable for everyday wear.",
    features: ["Canvas strap", "Date display", "Luminous hands", "Water-resistant"],
    image: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600&q=80",
  },
  {
    id: 12,
    name: "Explorer Canvas Navy",
    price: "KSh6,800.00",
    priceNum: 6800,
    category: "Men's Watch",
    brand: "Fossil",
    material: "Canvas",
    waterResistance: "5 ATM",
    warranty: "1 Year",
    size: "44mm",
    limited: false,
    description: "Navy canvas strap with maritime-inspired design. Perfect for casual outdoor activities.",
    features: ["Durable canvas", "Chronograph", "Date window", "Adjustable strap"],
    image: "https://images.unsplash.com/photo-1533139502658-0198f920d8e8?w=600&q=80",
  },
  {
    id: 13,
    name: "Adventurer Canvas Brown",
    price: "KSh7,200.00",
    priceNum: 7200,
    category: "Men's Watch",
    brand: "Citizen",
    material: "Canvas",
    waterResistance: "5 ATM",
    warranty: "2 Years",
    size: "43mm",
    limited: false,
    description: "Brown canvas strap with vintage military styling. Built tough for outdoor adventures.",
    features: ["Military-inspired", "Scratch-resistant", "Canvas strap", "Luminous markers"],
    image: "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=600&q=80",
  },
  {
    id: 14,
    name: "Nomad Canvas Gray",
    price: "KSh6,500.00",
    priceNum: 6500,
    category: "Men's Watch",
    brand: "Seiko",
    material: "Canvas",
    waterResistance: "3 ATM",
    warranty: "1 Year",
    size: "42mm",
    limited: false,
    description: "Sleek gray canvas strap with modern minimalist dial. Comfortable for all-day wear.",
    features: ["Minimalist design", "Canvas strap", "Date display", "Japanese movement"],
    image: "https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?w=600&q=80",
  },
  {
    id: 15,
    name: "Voyager Canvas Olive",
    price: "KSh7,000.00",
    priceNum: 7000,
    category: "Men's Watch",
    brand: "Hamilton",
    material: "Canvas",
    waterResistance: "5 ATM",
    warranty: "2 Years",
    size: "44mm",
    limited: false,
    description: "Olive canvas strap with tactical field watch design. Durable and functional.",
    features: ["Field watch style", "Canvas strap", "Luminous hands", "Date display"],
    image: "https://images.unsplash.com/photo-1511370235399-1802cae1d32f?w=600&q=80",
  },
  {
    id: 16,
    name: "Ranger Canvas Tan",
    price: "KSh6,800.00",
    priceNum: 6800,
    category: "Men's Watch",
    brand: "Bulova",
    material: "Canvas",
    waterResistance: "3 ATM",
    warranty: "1 Year",
    size: "42mm",
    limited: false,
    description: "Tan canvas strap with classic field watch aesthetics. Perfect for outdoor enthusiasts.",
    features: ["Canvas strap", "Easy-read dial", "Date window", "Water-resistant"],
    image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&q=80",
  },
  
  // Men's Metallic Collection
  {
    id: 31,
    name: "Steel Master Silver",
    price: "KSh10,500.00",
    priceNum: 10500,
    category: "Men's Watch",
    brand: "Tag Heuer",
    material: "Metallic",
    waterResistance: "10 ATM",
    warranty: "2 Years",
    size: "42mm",
    limited: false,
    description: "Premium stainless steel watch with sophisticated dial. Perfect for business and formal occasions.",
    features: ["Stainless steel", "Sapphire crystal", "Chronograph", "Water-resistant"],
    image: "https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=600&q=80",
  },
  {
    id: 32,
    name: "Titanium Pro Black",
    price: "KSh12,200.00",
    priceNum: 12200,
    category: "Men's Watch",
    brand: "Casio",
    material: "Metallic",
    waterResistance: "20 ATM",
    warranty: "2 Years",
    size: "44mm",
    limited: false,
    description: "Lightweight titanium construction with black ion plating. Built for professionals.",
    features: ["Titanium case", "Black ion plating", "Scratch-resistant", "Chronograph"],
    image: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=600&q=80",
  },
  {
    id: 33,
    name: "Chrome Elite Gold",
    price: "KSh11,800.00",
    priceNum: 11800,
    category: "Men's Watch",
    brand: "Citizen",
    material: "Metallic",
    waterResistance: "10 ATM",
    warranty: "2 Years",
    size: "42mm",
    limited: false,
    description: "Gold-tone stainless steel with elegant dial. Makes a statement of success.",
    features: ["Gold-tone steel", "Date display", "Luminous hands", "Water-resistant"],
    image: "https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=600&q=80",
  },
  {
    id: 34,
    name: "Metal Fusion Gray",
    price: "KSh10,800.00",
    priceNum: 10800,
    category: "Men's Watch",
    brand: "Seiko",
    material: "Metallic",
    waterResistance: "10 ATM",
    warranty: "2 Years",
    size: "43mm",
    limited: false,
    description: "Gunmetal gray finish with modern design. Perfect blend of style and function.",
    features: ["Gunmetal finish", "Chronograph", "Date display", "Anti-reflective crystal"],
    image: "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=600&q=80",
  },
  {
    id: 35,
    name: "Alloy Supreme Rose Gold",
    price: "KSh11,500.00",
    priceNum: 11500,
    category: "Men's Watch",
    brand: "Bulova",
    material: "Metallic",
    waterResistance: "5 ATM",
    warranty: "2 Years",
    size: "42mm",
    limited: false,
    description: "Rose gold plated stainless steel with refined elegance. Contemporary luxury design.",
    features: ["Rose gold plating", "Precision movement", "Date window", "Scratch-resistant"],
    image: "https://images.unsplash.com/photo-1533139502658-0198f920d8e8?w=600&q=80",
  },
  {
    id: 36,
    name: "Steel Precision Two-Tone",
    price: "KSh11,000.00",
    priceNum: 11000,
    category: "Men's Watch",
    brand: "Hamilton",
    material: "Metallic",
    waterResistance: "10 ATM",
    warranty: "2 Years",
    size: "42mm",
    limited: false,
    description: "Two-tone stainless steel bracelet with classic styling. Timeless sophistication.",
    features: ["Two-tone steel", "Date display", "Luminous markers", "Water-resistant"],
    image: "https://images.unsplash.com/photo-1511370235399-1802cae1d32f?w=600&q=80",
  },
  
  // Women's Watches
  {
    id: 41,
    name: "Rose Gold Elegance",
    price: "KSh6,500.00",
    priceNum: 6500,
    category: "Women's Watch",
    brand: "Michael Kors",
    size: "36mm",
    limited: false,
    material: "Stainless Steel",
    waterResistance: "5 ATM",
    warranty: "1 Year",
    description: "Elegant rose gold watch with refined details and feminine charm.",
    features: ["Quartz Movement", "Rose gold plating", "Crystal accents", "Free battery replacement"],
    image: "https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=600&q=80",
  },
  {
    id: 42,
    name: "Diamond Bezel",
    price: "KSh9,200.00",
    priceNum: 9200,
    category: "Women's Watch",
    brand: "Cartier",
    size: "32mm",
    limited: true,
    material: "Stainless Steel",
    waterResistance: "3 ATM",
    warranty: "2 Years",
    description: "Luxurious watch with diamond-studded bezel and premium craftsmanship.",
    features: ["Swiss Movement", "Diamond bezel", "Mother-of-pearl dial", "Free battery replacement"],
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80",
  },
  {
    id: 43,
    name: "Slim Leather",
    price: "KSh4,800.00",
    priceNum: 4800,
    category: "Women's Watch",
    brand: "Daniel Wellington",
    size: "34mm",
    limited: false,
    material: "Leather",
    waterResistance: "3 ATM",
    warranty: "1 Year",
    description: "Minimalist slim watch with genuine leather strap and clean design.",
    features: ["Quartz Movement", "Slim profile", "Interchangeable straps", "Free battery replacement"],
    image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=600&q=80",
  },
  {
    id: 44,
    name: "Pearl Mother",
    price: "KSh8,500.00",
    priceNum: 8500,
    category: "Women's Watch",
    brand: "Tissot",
    size: "30mm",
    limited: true,
    material: "Stainless Steel",
    waterResistance: "5 ATM",
    warranty: "2 Years",
    description: "Exquisite watch with mother-of-pearl dial and delicate design.",
    features: ["Swiss Quartz Movement", "Mother-of-pearl dial", "Sapphire crystal", "Free battery replacement"],
    image: "https://images.unsplash.com/photo-1610456123037-7d2be1a24e0d?w=600&q=80",
  },
  
  // Smart Watches
  {
    id: 45,
    name: "Apple Watch Series 9",
    price: "KSh7,800.00",
    priceNum: 7800,
    category: "Smart Watch",
    brand: "Apple",
    size: "41mm",
    limited: false,
    material: "Aluminum",
    waterResistance: "5 ATM",
    warranty: "1 Year",
    description: "Latest Apple Watch with advanced health tracking and connectivity features.",
    features: ["Always-On Retina Display", "Heart Rate Monitor", "GPS", "Water resistant"],
    image: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600&q=80",
  },
  {
    id: 46,
    name: "Galaxy Watch 6",
    price: "KSh6,200.00",
    priceNum: 6200,
    category: "Smart Watch",
    brand: "Samsung",
    size: "40mm",
    limited: false,
    material: "Aluminum",
    waterResistance: "5 ATM",
    warranty: "1 Year",
    description: "Samsung's flagship smartwatch with comprehensive health and fitness tracking.",
    features: ["AMOLED Display", "Sleep Tracking", "GPS", "Water resistant"],
    image: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&q=80",
  },
  
  // Women's Leather & Smart Watch Collection (Extended)
  {
    id: 47,
    name: "Galaxy Smart Watch Rose",
    price: "KSh4,500.00",
    priceNum: 4500,
    category: "Smart Watch",
    brand: "Samsung",
    material: "Aluminum",
    waterResistance: "5 ATM",
    warranty: "1 Year",
    size: "42mm",
    limited: false,
    description: "Rose gold Samsung smartwatch with health tracking. Style meets technology.",
    features: ["Rose gold finish", "Heart rate monitor", "GPS", "Fitness tracking"],
    image: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&q=80",
  },
  {
    id: 48,
    name: "Huawei GT Elegant Watch",
    price: "KSh3,800.00",
    priceNum: 3800,
    category: "Smart Watch",
    brand: "Huawei",
    material: "Stainless Steel",
    waterResistance: "5 ATM",
    warranty: "1 Year",
    size: "42mm",
    limited: false,
    description: "Huawei GT elegant smartwatch. Sophisticated design with smart features.",
    features: ["AMOLED screen", "14-day battery", "Health monitoring", "Water-resistant"],
    image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&q=80",
  },
  {
    id: 49,
    name: "Gold Chain Bracelet",
    price: "KSh5,200.00",
    priceNum: 5200,
    category: "Bracelet",
    brand: "Cartier",
    material: "Gold",
    size: "Medium",
    limited: false,
    description: "Elegant gold chain bracelet. Luxury jewelry piece for special occasions.",
    features: ["18K Gold Plated", "Adjustable", "Premium quality", "Gift box included"],
    image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&q=80",
  },
  {
    id: 50,
    name: "Diamond Tennis Bracelet",
    price: "KSh12,000.00",
    priceNum: 12000,
    category: "Bracelet",
    brand: "Tiffany & Co",
    material: "Silver",
    size: "Small",
    limited: true,
    description: "Diamond tennis bracelet with brilliant stones. Ultimate luxury statement.",
    features: ["Diamond stones", "Sterling silver", "Secure clasp", "Limited Edition"],
    image: "https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=600&q=80",
  },
  {
    id: 51,
    name: "Silver Bangle Set",
    price: "KSh3,800.00",
    priceNum: 3800,
    category: "Bangle",
    brand: "Pandora",
    material: "Silver",
    size: "Medium",
    limited: false,
    description: "Set of three silver bangles. Stack them for a trendy look.",
    features: ["Sterling silver", "Set of 3", "Stackable", "Hypoallergenic"],
    image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&q=80",
  },
  {
    id: 52,
    name: "Rose Gold Bangle",
    price: "KSh4,200.00",
    priceNum: 4200,
    category: "Bangle",
    brand: "Cartier",
    material: "Rose Gold",
    size: "Medium",
    limited: false,
    description: "Elegant rose gold bangle. Timeless piece for everyday wear.",
    features: ["Rose gold plated", "Smooth finish", "Comfortable fit", "Gift box included"],
    image: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=600&q=80",
  },
  {
    id: 53,
    name: "Gold Anklet Chain",
    price: "KSh2,800.00",
    priceNum: 2800,
    category: "Anklet",
    brand: "Tiffany & Co",
    material: "Gold",
    size: "9 inch",
    limited: false,
    description: "Delicate gold anklet chain. Perfect for summer style.",
    features: ["Gold plated", "Adjustable length", "Secure clasp", "Lightweight"],
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80",
  },
  {
    id: 54,
    name: "Silver Anklet Charm",
    price: "KSh2,200.00",
    priceNum: 2200,
    category: "Anklet",
    brand: "Pandora",
    material: "Silver",
    size: "10 inch",
    limited: false,
    description: "Silver anklet with charming details. Beach-ready accessory.",
    features: ["Sterling silver", "Charm details", "Adjustable", "Hypoallergenic"],
    image: "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=600&q=80",
  },
  {
    id: 55,
    name: "Leather Watch Strap Set",
    price: "KSh1,500.00",
    priceNum: 1500,
    category: "Strap",
    brand: "Universal",
    material: "Leather",
    size: "20mm",
    limited: false,
    description: "Versatile leather watch strap set. Multiple colors included.",
    features: ["Genuine leather", "Quick release", "Multiple colors", "Universal fit"],
    image: "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=600&q=80",
  },
  {
    id: 56,
    name: "Stainless Steel Strap",
    price: "KSh1,800.00",
    priceNum: 1800,
    category: "Strap",
    brand: "Universal",
    material: "Stainless Steel",
    size: "22mm",
    limited: false,
    description: "Premium stainless steel watch strap. Durable and stylish.",
    features: ["Stainless steel", "Adjustable links", "Butterfly clasp", "Universal fit"],
    image: "https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=600&q=80",
  },
  {
    id: 57,
    name: "Pearl Diamond Earrings",
    price: "KSh6,500.00",
    priceNum: 6500,
    category: "Jewelry",
    brand: "Cartier",
    material: "Pearl",
    size: "Small",
    limited: true,
    description: "Exquisite pearl and diamond earrings. Luxury statement pieces.",
    features: ["Pearl & diamond", "14K Gold", "Secure backs", "Limited Edition"],
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&q=80",
  },
  {
    id: 58,
    name: "Gold Hoop Earrings",
    price: "KSh3,500.00",
    priceNum: 3500,
    category: "Jewelry",
    brand: "Tiffany & Co",
    material: "Gold",
    size: "Medium",
    limited: false,
    description: "Classic gold hoop earrings. Versatile and timeless.",
    features: ["18K Gold Plated", "Medium size", "Secure clasp", "Hypoallergenic"],
    image: "https://images.unsplash.com/photo-1535556116002-6281ff3e9f36?w=600&q=80",
  },
  {
    id: 59,
    name: "Pearl Necklace Classic",
    price: "KSh7,200.00",
    priceNum: 7200,
    category: "Jewelry",
    brand: "Tiffany & Co",
    material: "Pearl",
    size: "18 inch",
    limited: false,
    description: "Classic pearl necklace strand. Timeless elegance.",
    features: ["Cultured pearls", "18-inch length", "Sterling clasp", "Gift box included"],
    image: "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=600&q=80",
  },
  {
    id: 60,
    name: "Diamond Pendant Necklace",
    price: "KSh9,500.00",
    priceNum: 9500,
    category: "Jewelry",
    brand: "Cartier",
    material: "Gold",
    size: "16 inch",
    limited: true,
    description: "Diamond pendant necklace on gold chain. Stunning luxury piece.",
    features: ["Diamond pendant", "14K Gold chain", "Adjustable length", "Limited Edition"],
    image: "https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?w=600&q=80",
  },
  
  // Women's Canvas Collection
  {
    id: 61,
    name: "Casual Canvas Mint",
    price: "KSh6,200.00",
    priceNum: 6200,
    category: "Women's Watch",
    brand: "Timex",
    material: "Canvas",
    waterResistance: "3 ATM",
    warranty: "1 Year",
    size: "34mm",
    limited: false,
    description: "Fresh mint canvas strap with playful design. Perfect for casual summer days.",
    features: ["Canvas strap", "Easy-read dial", "Water-resistant", "Adjustable"],
    image: "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=600&q=80",
  },
  {
    id: 62,
    name: "Summer Canvas Coral",
    price: "KSh6,500.00",
    priceNum: 6500,
    category: "Women's Watch",
    brand: "Fossil",
    material: "Canvas",
    waterResistance: "3 ATM",
    warranty: "1 Year",
    size: "36mm",
    limited: false,
    description: "Vibrant coral canvas strap with minimalist dial. Summer essential accessory.",
    features: ["Canvas strap", "Minimalist design", "Water-resistant", "Lightweight"],
    image: "https://images.unsplash.com/photo-1511370235399-1802cae1d32f?w=600&q=80",
  },
  {
    id: 63,
    name: "Fresh Canvas Sky Blue",
    price: "KSh6,300.00",
    priceNum: 6300,
    category: "Women's Watch",
    brand: "Casio",
    material: "Canvas",
    waterResistance: "3 ATM",
    warranty: "1 Year",
    size: "34mm",
    limited: false,
    description: "Sky blue canvas strap with modern dial. Refreshing everyday style.",
    features: ["Canvas strap", "Date display", "Water-resistant", "Comfortable fit"],
    image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&q=80",
  },
  {
    id: 64,
    name: "Breeze Canvas Lavender",
    price: "KSh6,800.00",
    priceNum: 6800,
    category: "Women's Watch",
    brand: "Seiko",
    material: "Canvas",
    waterResistance: "3 ATM",
    warranty: "1 Year",
    size: "35mm",
    limited: false,
    description: "Soft lavender canvas strap with elegant details. Feminine and comfortable.",
    features: ["Canvas strap", "Roman numerals", "Water-resistant", "Adjustable"],
    image: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=600&q=80",
  },
  {
    id: 65,
    name: "Sunshine Canvas Yellow",
    price: "KSh6,200.00",
    priceNum: 6200,
    category: "Women's Watch",
    brand: "Bulova",
    material: "Canvas",
    waterResistance: "3 ATM",
    warranty: "1 Year",
    size: "34mm",
    limited: false,
    description: "Cheerful yellow canvas strap with playful design. Brighten your day.",
    features: ["Canvas strap", "Easy-read dial", "Water-resistant", "Lightweight"],
    image: "https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=600&q=80",
  },
  {
    id: 66,
    name: "Blossom Canvas Pink",
    price: "KSh6,600.00",
    priceNum: 6600,
    category: "Women's Watch",
    brand: "Citizen",
    material: "Canvas",
    waterResistance: "3 ATM",
    warranty: "1 Year",
    size: "36mm",
    limited: false,
    description: "Soft pink canvas strap with delicate styling. Perfect spring accessory.",
    features: ["Canvas strap", "Date display", "Water-resistant", "Comfortable"],
    image: "https://images.unsplash.com/photo-1533139502658-0198f920d8e8?w=600&q=80",
  },
  
  // Women's Ceramic Collection
  {
    id: 71,
    name: "Porcelain Ceramic White",
    price: "KSh13,500.00",
    priceNum: 13500,
    category: "Women's Watch",
    brand: "Rado",
    material: "Ceramic",
    waterResistance: "5 ATM",
    warranty: "2 Years",
    size: "36mm",
    limited: false,
    description: "Pure white ceramic with scratch-resistant finish. Ultimate luxury and durability.",
    features: ["High-tech ceramic", "Scratch-resistant", "Date display", "Sapphire crystal"],
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80",
  },
  {
    id: 72,
    name: "Eclipse Ceramic Black",
    price: "KSh14,200.00",
    priceNum: 14200,
    category: "Women's Watch",
    brand: "Chanel",
    material: "Ceramic",
    waterResistance: "5 ATM",
    warranty: "2 Years",
    size: "38mm",
    limited: false,
    description: "Black ceramic with sophisticated design. Modern elegance meets durability.",
    features: ["Black ceramic", "Scratch-proof", "Date window", "Premium quality"],
    image: "https://images.unsplash.com/photo-1594534475808-b18fc33b045e?w=600&q=80",
  },
  {
    id: 73,
    name: "Pearl Ceramic Cream",
    price: "KSh13,800.00",
    priceNum: 13800,
    category: "Women's Watch",
    brand: "Tissot",
    material: "Ceramic",
    waterResistance: "5 ATM",
    warranty: "2 Years",
    size: "36mm",
    limited: false,
    description: "Cream ceramic with pearl accents. Soft luxury for discerning tastes.",
    features: ["Ceramic case", "Pearl dial", "Date display", "Scratch-resistant"],
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&q=80",
  },
  {
    id: 74,
    name: "Moonstone Ceramic Silver",
    price: "KSh14,500.00",
    priceNum: 14500,
    category: "Women's Watch",
    brand: "Longines",
    material: "Ceramic",
    waterResistance: "10 ATM",
    warranty: "2 Years",
    size: "38mm",
    limited: false,
    description: "Silver-tone ceramic with moonstone accents. Celestial elegance.",
    features: ["Silver ceramic", "Moonstone details", "Sapphire crystal", "Water-resistant"],
    image: "https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?w=600&q=80",
  },
  {
    id: 75,
    name: "Rose Ceramic Pink",
    price: "KSh13,900.00",
    priceNum: 13900,
    category: "Women's Watch",
    brand: "Omega",
    material: "Ceramic",
    waterResistance: "5 ATM",
    warranty: "2 Years",
    size: "36mm",
    limited: false,
    description: "Rose pink ceramic with feminine charm. Delicate strength and beauty.",
    features: ["Rose ceramic", "Crystal markers", "Date display", "Scratch-proof"],
    image: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600&q=80",
  },
  {
    id: 76,
    name: "Sapphire Ceramic Blue",
    price: "KSh14,000.00",
    priceNum: 14000,
    category: "Women's Watch",
    brand: "Tag Heuer",
    material: "Ceramic",
    waterResistance: "10 ATM",
    warranty: "2 Years",
    size: "38mm",
    limited: false,
    description: "Deep blue ceramic with sapphire accents. Ocean-inspired luxury.",
    features: ["Blue ceramic", "Sapphire accents", "Date window", "Water-resistant"],
    image: "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=600&q=80",
  },
  
  // Accessories - Bracelets
  {
    id: 81,
    name: "Love Bracelet",
    price: "KSh8,500.00",
    priceNum: 8500,
    category: "Bracelet",
    brand: "Cartier",
    size: "Medium",
    limited: true,
    material: "Gold Plated",
    description: "Iconic love bracelet with screw motif and timeless design.",
    features: ["18K Gold Plated", "Signature screw design", "Includes screwdriver", "Gift box included"],
    image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&q=80",
  },
  {
    id: 82,
    name: "Return to Tiffany",
    price: "KSh6,200.00",
    priceNum: 6200,
    category: "Bracelet",
    brand: "Tiffany & Co",
    size: "Small",
    limited: false,
    material: "Sterling Silver",
    description: "Classic Tiffany bracelet with heart tag charm and elegant chain.",
    features: ["Sterling Silver", "Heart tag charm", "Adjustable length", "Gift box included"],
    image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&q=80",
  },
  {
    id: 83,
    name: "Charm Bracelet",
    price: "KSh3,500.00",
    priceNum: 3500,
    category: "Bracelet",
    brand: "Pandora",
    size: "Medium",
    limited: false,
    material: "Sterling Silver",
    description: "Customizable charm bracelet perfect for collecting meaningful charms.",
    features: ["Sterling Silver", "Compatible with Pandora charms", "Secure clasp", "Gift box included"],
    image: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=600&q=80",
  },
  
  // Watch Straps
  {
    id: 84,
    name: "Leather Watch Strap",
    price: "KSh1,200.00",
    priceNum: 1200,
    category: "Strap",
    brand: "Universal",
    size: "20mm",
    limited: false,
    material: "Genuine Leather",
    description: "Premium leather watch strap compatible with most standard watches.",
    features: ["Genuine Leather", "Multiple colors", "Quick release pins", "Universal fit"],
    image: "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=600&q=80",
  },
  {
    id: 85,
    name: "Metal Link Bracelet",
    price: "KSh2,800.00",
    priceNum: 2800,
    category: "Strap",
    brand: "Universal",
    size: "22mm",
    limited: false,
    material: "Stainless Steel",
    description: "Stainless steel link bracelet with adjustable sizing.",
    features: ["Stainless Steel", "Butterfly clasp", "Adjustable links", "Universal fit"],
    image: "https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?w=600&q=80",
  },
  
  // Bangles
  {
    id: 86,
    name: "Gold Bangle",
    price: "KSh4,500.00",
    priceNum: 4500,
    category: "Bangle",
    brand: "Universal",
    size: "Medium",
    limited: false,
    material: "Gold Plated",
    description: "Elegant gold bangle perfect for stacking or wearing solo.",
    features: ["18K Gold Plated", "Smooth finish", "Comfortable fit", "Gift box included"],
    image: "https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?w=600&q=80",
  },
  {
    id: 87,
    name: "Rose Gold Bangle",
    price: "KSh4,200.00",
    priceNum: 4200,
    category: "Bangle",
    brand: "Cartier",
    material: "Rose Gold",
    size: "Medium",
    limited: false,
    description: "Elegant rose gold bangle with smooth finish. Perfect for stacking.",
    features: ["Rose gold plated", "Smooth finish", "Comfortable fit", "Gift box included"],
    image: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=600&q=80",
  },
  {
    id: 88,
    name: "Gold Anklet Chain",
    price: "KSh2,800.00",
    priceNum: 2800,
    category: "Anklet",
    brand: "Tiffany & Co",
    material: "Gold",
    size: "9 inch",
    limited: false,
    description: "Delicate gold anklet chain. Perfect summer accessory.",
    features: ["Gold plated", "Adjustable length", "Secure clasp", "Lightweight"],
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80",
  },
  {
    id: 89,
    name: "Silver Anklet Charm",
    price: "KSh2,200.00",
    priceNum: 2200,
    category: "Anklet",
    brand: "Pandora",
    material: "Silver",
    size: "10 inch",
    limited: false,
    description: "Silver anklet with charming details. Beach-ready style.",
    features: ["Sterling silver", "Charm details", "Adjustable", "Hypoallergenic"],
    image: "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=600&q=80",
  },
  {
    id: 90,
    name: "Pearl Diamond Earrings",
    price: "KSh6,500.00",
    priceNum: 6500,
    category: "Jewelry",
    brand: "Cartier",
    material: "Pearl",
    size: "Small",
    limited: true,
    description: "Exquisite pearl and diamond earrings. Luxury statement.",
    features: ["Pearl & diamond", "14K Gold", "Secure backs", "Limited Edition"],
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&q=80",
  },
  
  // Jewelry - Earrings
  {
    id: 91,
    name: "Diamond Stud Earrings",
    price: "KSh6,500.00",
    priceNum: 6500,
    category: "Jewelry",
    brand: "Tiffany & Co",
    material: "Gold",
    limited: false,
    description: "Classic diamond stud earrings in 14K gold. Timeless elegance for any occasion.",
    features: ["14K Gold", "Diamond studs", "Push-back closure", "Gift box included"],
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&q=80",
  },
  {
    id: 92,
    name: "Gold Hoop Earrings",
    price: "KSh4,200.00",
    priceNum: 4200,
    category: "Jewelry",
    brand: "Pandora",
    material: "Gold",
    limited: false,
    description: "Medium-sized gold hoop earrings. Versatile style for everyday wear.",
    features: ["18K Gold Plated", "Hoop design", "Secure clasp", "Hypoallergenic"],
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80",
  },
  {
    id: 93,
    name: "Pearl Drop Earrings",
    price: "KSh5,800.00",
    priceNum: 5800,
    category: "Jewelry",
    brand: "Mikimoto",
    material: "Silver",
    limited: false,
    description: "Elegant pearl drop earrings with sterling silver. Perfect for formal events.",
    features: ["Sterling Silver", "Cultured pearls", "Drop design", "Gift box included"],
    image: "https://images.unsplash.com/photo-1630019852942-f89202989a59?w=600&q=80",
  },
  {
    id: 94,
    name: "Crystal Chandelier Earrings",
    price: "KSh7,500.00",
    priceNum: 7500,
    category: "Jewelry",
    brand: "Swarovski",
    material: "Crystal",
    limited: false,
    description: "Stunning crystal chandelier earrings. Statement pieces for special occasions.",
    features: ["Swarovski crystals", "Chandelier style", "Rhodium plated", "Gift box included"],
    image: "https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=600&q=80",
  },
  {
    id: 95,
    name: "Silver Geometric Earrings",
    price: "KSh3,900.00",
    priceNum: 3900,
    category: "Jewelry",
    brand: "Modern Style",
    material: "Silver",
    limited: false,
    description: "Modern geometric design in sterling silver. Contemporary elegance.",
    features: ["Sterling Silver", "Geometric design", "Push-back closure", "Hypoallergenic"],
    image: "https://images.unsplash.com/photo-1564858250557-a0b6729d0650?w=600&q=80",
  },
  {
    id: 96,
    name: "Rose Gold Dangle Earrings",
    price: "KSh4,800.00",
    priceNum: 4800,
    category: "Jewelry",
    brand: "Monica Vinader",
    material: "Rose Gold",
    limited: false,
    description: "Delicate rose gold dangle earrings. Feminine and sophisticated.",
    features: ["Rose Gold Plated", "Dangle style", "Secure hooks", "Gift box included"],
    image: "https://images.unsplash.com/photo-1603561596112-0a132b757442?w=600&q=80",
  },
  
  // Jewelry - Necklaces
  {
    id: 101,
    name: "Gold Chain Necklace",
    price: "KSh7,500.00",
    priceNum: 7500,
    category: "Jewelry",
    brand: "Cartier",
    material: "Gold",
    limited: false,
    description: "Classic gold chain necklace. Timeless piece for layering or wearing solo.",
    features: ["18K Gold Plated", "Adjustable length", "Lobster clasp", "Gift box included"],
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80",
  },
  {
    id: 102,
    name: "Pearl Strand Necklace",
    price: "KSh8,200.00",
    priceNum: 8200,
    category: "Jewelry",
    brand: "Mikimoto",
    material: "Pearl",
    limited: false,
    description: "Elegant cultured pearl strand necklace. Classic sophistication.",
    features: ["Cultured pearls", "Sterling silver clasp", "18-inch length", "Gift box included"],
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&q=80",
  },
  {
    id: 103,
    name: "Diamond Pendant Necklace",
    price: "KSh12,500.00",
    priceNum: 12500,
    category: "Jewelry",
    brand: "Tiffany & Co",
    material: "Gold",
    limited: false,
    description: "Stunning diamond pendant on delicate gold chain. Luxury statement piece.",
    features: ["14K Gold", "Diamond pendant", "Adjustable chain", "Certificate included"],
    image: "https://images.unsplash.com/photo-1630019852942-f89202989a59?w=600&q=80",
  },
  {
    id: 104,
    name: "Silver Choker Necklace",
    price: "KSh4,800.00",
    priceNum: 4800,
    category: "Jewelry",
    brand: "Modern Style",
    material: "Silver",
    limited: false,
    description: "Contemporary silver choker necklace. Modern minimalist style.",
    features: ["Sterling Silver", "Choker style", "Adjustable fit", "Hypoallergenic"],
    image: "https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=600&q=80",
  },
  {
    id: 105,
    name: "Rose Gold Locket Necklace",
    price: "KSh6,900.00",
    priceNum: 6900,
    category: "Jewelry",
    brand: "Monica Vinader",
    material: "Rose Gold",
    limited: false,
    description: "Romantic rose gold locket necklace. Keep memories close to your heart.",
    features: ["Rose Gold Plated", "Photo locket", "Adjustable chain", "Gift box included"],
    image: "https://images.unsplash.com/photo-1564858250557-a0b6729d0650?w=600&q=80",
  },
  {
    id: 106,
    name: "Crystal Statement Necklace",
    price: "KSh9,200.00",
    priceNum: 9200,
    category: "Jewelry",
    brand: "Swarovski",
    material: "Crystal",
    limited: false,
    description: "Bold crystal statement necklace. Eye-catching piece for special occasions.",
    features: ["Swarovski crystals", "Statement design", "Rhodium plated", "Gift box included"],
    image: "https://images.unsplash.com/photo-1603561596112-0a132b757442?w=600&q=80",
  },
  
  // Accessories - Wallets
  {
    id: 111,
    name: "Leather Bi-Fold Wallet",
    price: "KSh3,500.00",
    priceNum: 3500,
    category: "Wallet",
    brand: "Fossil",
    material: "Leather",
    limited: false,
    description: "Classic leather bi-fold wallet with multiple card slots. Timeless style and functionality.",
    features: ["Genuine leather", "6 card slots", "Bi-fold design", "Gift box included"],
    image: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&q=80",
  },
  {
    id: 112,
    name: "Slim Card Holder",
    price: "KSh2,200.00",
    priceNum: 2200,
    category: "Wallet",
    brand: "Bellroy",
    material: "Leather",
    limited: false,
    description: "Minimalist slim card holder. Perfect for carrying essentials only.",
    features: ["Premium leather", "4 card slots", "Slim design", "RFID protection"],
    image: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=600&q=80",
  },
  {
    id: 113,
    name: "Executive Leather Wallet",
    price: "KSh4,800.00",
    priceNum: 4800,
    category: "Wallet",
    brand: "Montblanc",
    material: "Leather",
    limited: false,
    description: "Premium executive leather wallet. Luxury craftsmanship and style.",
    features: ["Italian leather", "8 card slots", "Coin pocket", "Gift box included"],
    image: "https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=600&q=80",
  },
  {
    id: 114,
    name: "RFID Blocking Wallet",
    price: "KSh3,900.00",
    priceNum: 3900,
    category: "Wallet",
    brand: "Ridge",
    material: "Leather",
    limited: false,
    description: "Modern RFID blocking wallet. Security meets style.",
    features: ["RFID blocking", "Genuine leather", "6 card slots", "ID window"],
    image: "https://images.unsplash.com/photo-1624680596473-c2c0e53b8f18?w=600&q=80",
  },
  {
    id: 115,
    name: "Money Clip Wallet",
    price: "KSh2,800.00",
    priceNum: 2800,
    category: "Wallet",
    brand: "Bellroy",
    material: "Leather",
    limited: false,
    description: "Sleek money clip wallet. Minimalist design for modern professionals.",
    features: ["Premium leather", "Money clip", "4 card slots", "Slim profile"],
    image: "https://images.unsplash.com/photo-1626897505254-e0f811aa9bf7?w=600&q=80",
  },
  {
    id: 116,
    name: "Travel Document Wallet",
    price: "KSh5,200.00",
    priceNum: 5200,
    category: "Wallet",
    brand: "Fossil",
    material: "Leather",
    limited: false,
    description: "Spacious travel document wallet. Keep all travel essentials organized.",
    features: ["Genuine leather", "Passport slots", "Multiple compartments", "RFID protection"],
    image: "https://images.unsplash.com/photo-1624680595933-8c4ab4f8d3b2?w=600&q=80",
  },
]

export function getProductById(id: number) {
  return products.find((p) => p.id === id)
}

export function getProductsByCategory(category: string) {
  return products.filter((p) => p.category?.toLowerCase() === category.toLowerCase())
}

